package com.cr.art.dao.model;

import java.util.Date;

public class ArtCategory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_category.category_id
     *
     * @mbggenerated
     */
    private String categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_category.category_name
     *
     * @mbggenerated
     */
    private String categoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_category.categroy_desc
     *
     * @mbggenerated
     */
    private String categroyDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_category.insert_time
     *
     * @mbggenerated
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column art_category.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_category.category_id
     *
     * @return the value of art_category.category_id
     *
     * @mbggenerated
     */
    public String getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_category.category_id
     *
     * @param categoryId the value for art_category.category_id
     *
     * @mbggenerated
     */
    public void setCategoryId(String categoryId) {
        this.categoryId = categoryId == null ? null : categoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_category.category_name
     *
     * @return the value of art_category.category_name
     *
     * @mbggenerated
     */
    public String getCategoryName() {
        return categoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_category.category_name
     *
     * @param categoryName the value for art_category.category_name
     *
     * @mbggenerated
     */
    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName == null ? null : categoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_category.categroy_desc
     *
     * @return the value of art_category.categroy_desc
     *
     * @mbggenerated
     */
    public String getCategroyDesc() {
        return categroyDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_category.categroy_desc
     *
     * @param categroyDesc the value for art_category.categroy_desc
     *
     * @mbggenerated
     */
    public void setCategroyDesc(String categroyDesc) {
        this.categroyDesc = categroyDesc == null ? null : categroyDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_category.insert_time
     *
     * @return the value of art_category.insert_time
     *
     * @mbggenerated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_category.insert_time
     *
     * @param insertTime the value for art_category.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column art_category.update_time
     *
     * @return the value of art_category.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column art_category.update_time
     *
     * @param updateTime the value for art_category.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}