package com.cr.art.dao.model;

import java.util.Date;

public class ArtFocusArt {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_art.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_art.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_art.art_id
     *
     * @mbggenerated
     */
    private String artId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_art.focus_time
     *
     * @mbggenerated
     */
    private Date focusTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_art.insert_time
     *
     * @mbggenerated
     */
    private Date insertTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_focus_art.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_art.id
     *
     * @return the value of user_focus_art.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_art.id
     *
     * @param id the value for user_focus_art.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_art.user_id
     *
     * @return the value of user_focus_art.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_art.user_id
     *
     * @param userId the value for user_focus_art.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_art.art_id
     *
     * @return the value of user_focus_art.art_id
     *
     * @mbggenerated
     */
    public String getArtId() {
        return artId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_art.art_id
     *
     * @param artId the value for user_focus_art.art_id
     *
     * @mbggenerated
     */
    public void setArtId(String artId) {
        this.artId = artId == null ? null : artId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_art.focus_time
     *
     * @return the value of user_focus_art.focus_time
     *
     * @mbggenerated
     */
    public Date getFocusTime() {
        return focusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_art.focus_time
     *
     * @param focusTime the value for user_focus_art.focus_time
     *
     * @mbggenerated
     */
    public void setFocusTime(Date focusTime) {
        this.focusTime = focusTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_art.insert_time
     *
     * @return the value of user_focus_art.insert_time
     *
     * @mbggenerated
     */
    public Date getInsertTime() {
        return insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_art.insert_time
     *
     * @param insertTime the value for user_focus_art.insert_time
     *
     * @mbggenerated
     */
    public void setInsertTime(Date insertTime) {
        this.insertTime = insertTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_focus_art.update_time
     *
     * @return the value of user_focus_art.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_focus_art.update_time
     *
     * @param updateTime the value for user_focus_art.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}