package com.cr.art.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class ArtInfoM {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.art_id
	 * @mbggenerated
	 */
	private String artId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.author_id
	 * @mbggenerated
	 */
	private String authorId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.category
	 * @mbggenerated
	 */
	private Integer category;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.price
	 * @mbggenerated
	 */
	private BigDecimal price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.tag
	 * @mbggenerated
	 */
	private String tag;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.des
	 * @mbggenerated
	 */
	private String des;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.create_time
	 * @mbggenerated
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.insert_time
	 * @mbggenerated
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_info.update_time
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.art_id
	 * @return  the value of art_info.art_id
	 * @mbggenerated
	 */
	public String getArtId() {
		return artId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.art_id
	 * @param artId  the value for art_info.art_id
	 * @mbggenerated
	 */
	public void setArtId(String artId) {
		this.artId = artId == null ? null : artId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.author_id
	 * @return  the value of art_info.author_id
	 * @mbggenerated
	 */
	public String getAuthorId() {
		return authorId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.author_id
	 * @param authorId  the value for art_info.author_id
	 * @mbggenerated
	 */
	public void setAuthorId(String authorId) {
		this.authorId = authorId == null ? null : authorId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.name
	 * @return  the value of art_info.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.name
	 * @param name  the value for art_info.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name == null ? null : name.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.category
	 * @return  the value of art_info.category
	 * @mbggenerated
	 */
	public Integer getCategory() {
		return category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.category
	 * @param category  the value for art_info.category
	 * @mbggenerated
	 */
	public void setCategory(Integer category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.price
	 * @return  the value of art_info.price
	 * @mbggenerated
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.price
	 * @param price  the value for art_info.price
	 * @mbggenerated
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.tag
	 * @return  the value of art_info.tag
	 * @mbggenerated
	 */
	public String getTag() {
		return tag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.tag
	 * @param tag  the value for art_info.tag
	 * @mbggenerated
	 */
	public void setTag(String tag) {
		this.tag = tag == null ? null : tag.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.des
	 * @return  the value of art_info.des
	 * @mbggenerated
	 */
	public String getDes() {
		return des;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.des
	 * @param des  the value for art_info.des
	 * @mbggenerated
	 */
	public void setDes(String des) {
		this.des = des == null ? null : des.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.create_time
	 * @return  the value of art_info.create_time
	 * @mbggenerated
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.create_time
	 * @param createTime  the value for art_info.create_time
	 * @mbggenerated
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.insert_time
	 * @return  the value of art_info.insert_time
	 * @mbggenerated
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.insert_time
	 * @param insertTime  the value for art_info.insert_time
	 * @mbggenerated
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_info.update_time
	 * @return  the value of art_info.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_info.update_time
	 * @param updateTime  the value for art_info.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}