package com.cr.art.dao.model;

import java.util.Date;

public class ArtPicM {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.id
	 * @mbggenerated
	 */
	private String id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.art_id
	 * @mbggenerated
	 */
	private String artId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.pic_url
	 * @mbggenerated
	 */
	private String picUrl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.is_front
	 * @mbggenerated
	 */
	private Boolean isFront;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.is_exhibition
	 * @mbggenerated
	 */
	private Boolean isExhibition;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.width
	 * @mbggenerated
	 */
	private Integer width;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.height
	 * @mbggenerated
	 */
	private Integer height;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.insert_time
	 * @mbggenerated
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_pic.update_time
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.id
	 * @return  the value of art_pic.id
	 * @mbggenerated
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.id
	 * @param id  the value for art_pic.id
	 * @mbggenerated
	 */
	public void setId(String id) {
		this.id = id == null ? null : id.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.art_id
	 * @return  the value of art_pic.art_id
	 * @mbggenerated
	 */
	public String getArtId() {
		return artId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.art_id
	 * @param artId  the value for art_pic.art_id
	 * @mbggenerated
	 */
	public void setArtId(String artId) {
		this.artId = artId == null ? null : artId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.pic_url
	 * @return  the value of art_pic.pic_url
	 * @mbggenerated
	 */
	public String getPicUrl() {
		return picUrl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.pic_url
	 * @param picUrl  the value for art_pic.pic_url
	 * @mbggenerated
	 */
	public void setPicUrl(String picUrl) {
		this.picUrl = picUrl == null ? null : picUrl.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.is_front
	 * @return  the value of art_pic.is_front
	 * @mbggenerated
	 */
	public Boolean getIsFront() {
		return isFront;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.is_front
	 * @param isFront  the value for art_pic.is_front
	 * @mbggenerated
	 */
	public void setIsFront(Boolean isFront) {
		this.isFront = isFront;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.is_exhibition
	 * @return  the value of art_pic.is_exhibition
	 * @mbggenerated
	 */
	public Boolean getIsExhibition() {
		return isExhibition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.is_exhibition
	 * @param isExhibition  the value for art_pic.is_exhibition
	 * @mbggenerated
	 */
	public void setIsExhibition(Boolean isExhibition) {
		this.isExhibition = isExhibition;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.width
	 * @return  the value of art_pic.width
	 * @mbggenerated
	 */
	public Integer getWidth() {
		return width;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.width
	 * @param width  the value for art_pic.width
	 * @mbggenerated
	 */
	public void setWidth(Integer width) {
		this.width = width;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.height
	 * @return  the value of art_pic.height
	 * @mbggenerated
	 */
	public Integer getHeight() {
		return height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.height
	 * @param height  the value for art_pic.height
	 * @mbggenerated
	 */
	public void setHeight(Integer height) {
		this.height = height;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.insert_time
	 * @return  the value of art_pic.insert_time
	 * @mbggenerated
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.insert_time
	 * @param insertTime  the value for art_pic.insert_time
	 * @mbggenerated
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_pic.update_time
	 * @return  the value of art_pic.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_pic.update_time
	 * @param updateTime  the value for art_pic.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}