package com.cr.art.dao.model;

import java.util.Date;

public class ArtPraiseArtM {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user_praise_art.praise_id
	 * @mbggenerated
	 */
	private String praiseId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user_praise_art.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user_praise_art.art_id
	 * @mbggenerated
	 */
	private String artId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user_praise_art.praise_art_id
	 * @mbggenerated
	 */
	private String praiseArtId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user_praise_art.praise_time
	 * @mbggenerated
	 */
	private Date praiseTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user_praise_art.insert_time
	 * @mbggenerated
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user_praise_art.update_time
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user_praise_art.praise_id
	 * @return  the value of art_user_praise_art.praise_id
	 * @mbggenerated
	 */
	public String getPraiseId() {
		return praiseId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user_praise_art.praise_id
	 * @param praiseId  the value for art_user_praise_art.praise_id
	 * @mbggenerated
	 */
	public void setPraiseId(String praiseId) {
		this.praiseId = praiseId == null ? null : praiseId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user_praise_art.user_id
	 * @return  the value of art_user_praise_art.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user_praise_art.user_id
	 * @param userId  the value for art_user_praise_art.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user_praise_art.art_id
	 * @return  the value of art_user_praise_art.art_id
	 * @mbggenerated
	 */
	public String getArtId() {
		return artId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user_praise_art.art_id
	 * @param artId  the value for art_user_praise_art.art_id
	 * @mbggenerated
	 */
	public void setArtId(String artId) {
		this.artId = artId == null ? null : artId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user_praise_art.praise_art_id
	 * @return  the value of art_user_praise_art.praise_art_id
	 * @mbggenerated
	 */
	public String getPraiseArtId() {
		return praiseArtId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user_praise_art.praise_art_id
	 * @param praiseArtId  the value for art_user_praise_art.praise_art_id
	 * @mbggenerated
	 */
	public void setPraiseArtId(String praiseArtId) {
		this.praiseArtId = praiseArtId == null ? null : praiseArtId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user_praise_art.praise_time
	 * @return  the value of art_user_praise_art.praise_time
	 * @mbggenerated
	 */
	public Date getPraiseTime() {
		return praiseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user_praise_art.praise_time
	 * @param praiseTime  the value for art_user_praise_art.praise_time
	 * @mbggenerated
	 */
	public void setPraiseTime(Date praiseTime) {
		this.praiseTime = praiseTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user_praise_art.insert_time
	 * @return  the value of art_user_praise_art.insert_time
	 * @mbggenerated
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user_praise_art.insert_time
	 * @param insertTime  the value for art_user_praise_art.insert_time
	 * @mbggenerated
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user_praise_art.update_time
	 * @return  the value of art_user_praise_art.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user_praise_art.update_time
	 * @param updateTime  the value for art_user_praise_art.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}