package com.cr.art.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ArtPraiseArtMExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public ArtPraiseArtMExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPraiseIdIsNull() {
            addCriterion("praise_id is null");
            return (Criteria) this;
        }

        public Criteria andPraiseIdIsNotNull() {
            addCriterion("praise_id is not null");
            return (Criteria) this;
        }

        public Criteria andPraiseIdEqualTo(String value) {
            addCriterion("praise_id =", value, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdNotEqualTo(String value) {
            addCriterion("praise_id <>", value, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdGreaterThan(String value) {
            addCriterion("praise_id >", value, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdGreaterThanOrEqualTo(String value) {
            addCriterion("praise_id >=", value, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdLessThan(String value) {
            addCriterion("praise_id <", value, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdLessThanOrEqualTo(String value) {
            addCriterion("praise_id <=", value, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdLike(String value) {
            addCriterion("praise_id like", value, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdNotLike(String value) {
            addCriterion("praise_id not like", value, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdIn(List<String> values) {
            addCriterion("praise_id in", values, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdNotIn(List<String> values) {
            addCriterion("praise_id not in", values, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdBetween(String value1, String value2) {
            addCriterion("praise_id between", value1, value2, "praiseId");
            return (Criteria) this;
        }

        public Criteria andPraiseIdNotBetween(String value1, String value2) {
            addCriterion("praise_id not between", value1, value2, "praiseId");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(String value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(String value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(String value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(String value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(String value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLike(String value) {
            addCriterion("user_id like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotLike(String value) {
            addCriterion("user_id not like", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<String> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<String> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(String value1, String value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(String value1, String value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andArtIdIsNull() {
            addCriterion("art_id is null");
            return (Criteria) this;
        }

        public Criteria andArtIdIsNotNull() {
            addCriterion("art_id is not null");
            return (Criteria) this;
        }

        public Criteria andArtIdEqualTo(String value) {
            addCriterion("art_id =", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdNotEqualTo(String value) {
            addCriterion("art_id <>", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdGreaterThan(String value) {
            addCriterion("art_id >", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdGreaterThanOrEqualTo(String value) {
            addCriterion("art_id >=", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdLessThan(String value) {
            addCriterion("art_id <", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdLessThanOrEqualTo(String value) {
            addCriterion("art_id <=", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdLike(String value) {
            addCriterion("art_id like", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdNotLike(String value) {
            addCriterion("art_id not like", value, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdIn(List<String> values) {
            addCriterion("art_id in", values, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdNotIn(List<String> values) {
            addCriterion("art_id not in", values, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdBetween(String value1, String value2) {
            addCriterion("art_id between", value1, value2, "artId");
            return (Criteria) this;
        }

        public Criteria andArtIdNotBetween(String value1, String value2) {
            addCriterion("art_id not between", value1, value2, "artId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdIsNull() {
            addCriterion("praise_art_id is null");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdIsNotNull() {
            addCriterion("praise_art_id is not null");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdEqualTo(String value) {
            addCriterion("praise_art_id =", value, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdNotEqualTo(String value) {
            addCriterion("praise_art_id <>", value, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdGreaterThan(String value) {
            addCriterion("praise_art_id >", value, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdGreaterThanOrEqualTo(String value) {
            addCriterion("praise_art_id >=", value, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdLessThan(String value) {
            addCriterion("praise_art_id <", value, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdLessThanOrEqualTo(String value) {
            addCriterion("praise_art_id <=", value, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdLike(String value) {
            addCriterion("praise_art_id like", value, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdNotLike(String value) {
            addCriterion("praise_art_id not like", value, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdIn(List<String> values) {
            addCriterion("praise_art_id in", values, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdNotIn(List<String> values) {
            addCriterion("praise_art_id not in", values, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdBetween(String value1, String value2) {
            addCriterion("praise_art_id between", value1, value2, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseArtIdNotBetween(String value1, String value2) {
            addCriterion("praise_art_id not between", value1, value2, "praiseArtId");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeIsNull() {
            addCriterion("praise_time is null");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeIsNotNull() {
            addCriterion("praise_time is not null");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeEqualTo(Date value) {
            addCriterion("praise_time =", value, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeNotEqualTo(Date value) {
            addCriterion("praise_time <>", value, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeGreaterThan(Date value) {
            addCriterion("praise_time >", value, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("praise_time >=", value, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeLessThan(Date value) {
            addCriterion("praise_time <", value, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeLessThanOrEqualTo(Date value) {
            addCriterion("praise_time <=", value, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeIn(List<Date> values) {
            addCriterion("praise_time in", values, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeNotIn(List<Date> values) {
            addCriterion("praise_time not in", values, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeBetween(Date value1, Date value2) {
            addCriterion("praise_time between", value1, value2, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andPraiseTimeNotBetween(Date value1, Date value2) {
            addCriterion("praise_time not between", value1, value2, "praiseTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIsNull() {
            addCriterion("insert_time is null");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIsNotNull() {
            addCriterion("insert_time is not null");
            return (Criteria) this;
        }

        public Criteria andInsertTimeEqualTo(Date value) {
            addCriterion("insert_time =", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotEqualTo(Date value) {
            addCriterion("insert_time <>", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeGreaterThan(Date value) {
            addCriterion("insert_time >", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("insert_time >=", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeLessThan(Date value) {
            addCriterion("insert_time <", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeLessThanOrEqualTo(Date value) {
            addCriterion("insert_time <=", value, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeIn(List<Date> values) {
            addCriterion("insert_time in", values, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotIn(List<Date> values) {
            addCriterion("insert_time not in", values, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeBetween(Date value1, Date value2) {
            addCriterion("insert_time between", value1, value2, "insertTime");
            return (Criteria) this;
        }

        public Criteria andInsertTimeNotBetween(Date value1, Date value2) {
            addCriterion("insert_time not between", value1, value2, "insertTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table art_user_praise_art
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table art_user_praise_art
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}