package com.cr.art.dao.model;

import java.util.Date;

public class ArtUserM {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.user_id
	 * @mbggenerated
	 */
	private String userId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.mobile
	 * @mbggenerated
	 */
	private String mobile;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.nickname
	 * @mbggenerated
	 */
	private String nickname;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.sex
	 * @mbggenerated
	 */
	private Integer sex;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.age
	 * @mbggenerated
	 */
	private Integer age;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.photo
	 * @mbggenerated
	 */
	private String photo;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.province
	 * @mbggenerated
	 */
	private String province;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.city
	 * @mbggenerated
	 */
	private String city;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.sign
	 * @mbggenerated
	 */
	private String sign;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.address
	 * @mbggenerated
	 */
	private String address;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.post_code
	 * @mbggenerated
	 */
	private String postCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.declaration
	 * @mbggenerated
	 */
	private String declaration;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.insert_time
	 * @mbggenerated
	 */
	private Date insertTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column art_user.update_time
	 * @mbggenerated
	 */
	private Date updateTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.user_id
	 * @return  the value of art_user.user_id
	 * @mbggenerated
	 */
	public String getUserId() {
		return userId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.user_id
	 * @param userId  the value for art_user.user_id
	 * @mbggenerated
	 */
	public void setUserId(String userId) {
		this.userId = userId == null ? null : userId.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.mobile
	 * @return  the value of art_user.mobile
	 * @mbggenerated
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.mobile
	 * @param mobile  the value for art_user.mobile
	 * @mbggenerated
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile == null ? null : mobile.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.password
	 * @return  the value of art_user.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.password
	 * @param password  the value for art_user.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password == null ? null : password.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.nickname
	 * @return  the value of art_user.nickname
	 * @mbggenerated
	 */
	public String getNickname() {
		return nickname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.nickname
	 * @param nickname  the value for art_user.nickname
	 * @mbggenerated
	 */
	public void setNickname(String nickname) {
		this.nickname = nickname == null ? null : nickname.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.sex
	 * @return  the value of art_user.sex
	 * @mbggenerated
	 */
	public Integer getSex() {
		return sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.sex
	 * @param sex  the value for art_user.sex
	 * @mbggenerated
	 */
	public void setSex(Integer sex) {
		this.sex = sex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.age
	 * @return  the value of art_user.age
	 * @mbggenerated
	 */
	public Integer getAge() {
		return age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.age
	 * @param age  the value for art_user.age
	 * @mbggenerated
	 */
	public void setAge(Integer age) {
		this.age = age;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.photo
	 * @return  the value of art_user.photo
	 * @mbggenerated
	 */
	public String getPhoto() {
		return photo;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.photo
	 * @param photo  the value for art_user.photo
	 * @mbggenerated
	 */
	public void setPhoto(String photo) {
		this.photo = photo == null ? null : photo.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.province
	 * @return  the value of art_user.province
	 * @mbggenerated
	 */
	public String getProvince() {
		return province;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.province
	 * @param province  the value for art_user.province
	 * @mbggenerated
	 */
	public void setProvince(String province) {
		this.province = province == null ? null : province.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.city
	 * @return  the value of art_user.city
	 * @mbggenerated
	 */
	public String getCity() {
		return city;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.city
	 * @param city  the value for art_user.city
	 * @mbggenerated
	 */
	public void setCity(String city) {
		this.city = city == null ? null : city.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.sign
	 * @return  the value of art_user.sign
	 * @mbggenerated
	 */
	public String getSign() {
		return sign;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.sign
	 * @param sign  the value for art_user.sign
	 * @mbggenerated
	 */
	public void setSign(String sign) {
		this.sign = sign == null ? null : sign.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.address
	 * @return  the value of art_user.address
	 * @mbggenerated
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.address
	 * @param address  the value for art_user.address
	 * @mbggenerated
	 */
	public void setAddress(String address) {
		this.address = address == null ? null : address.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.post_code
	 * @return  the value of art_user.post_code
	 * @mbggenerated
	 */
	public String getPostCode() {
		return postCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.post_code
	 * @param postCode  the value for art_user.post_code
	 * @mbggenerated
	 */
	public void setPostCode(String postCode) {
		this.postCode = postCode == null ? null : postCode.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.declaration
	 * @return  the value of art_user.declaration
	 * @mbggenerated
	 */
	public String getDeclaration() {
		return declaration;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.declaration
	 * @param declaration  the value for art_user.declaration
	 * @mbggenerated
	 */
	public void setDeclaration(String declaration) {
		this.declaration = declaration == null ? null : declaration.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.insert_time
	 * @return  the value of art_user.insert_time
	 * @mbggenerated
	 */
	public Date getInsertTime() {
		return insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.insert_time
	 * @param insertTime  the value for art_user.insert_time
	 * @mbggenerated
	 */
	public void setInsertTime(Date insertTime) {
		this.insertTime = insertTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column art_user.update_time
	 * @return  the value of art_user.update_time
	 * @mbggenerated
	 */
	public Date getUpdateTime() {
		return updateTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column art_user.update_time
	 * @param updateTime  the value for art_user.update_time
	 * @mbggenerated
	 */
	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}
}