package com.cr.art.dao.mapper;

import com.cr.art.dao.model.ArtCategory;
import com.cr.art.dao.model.ArtCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArtCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int countByExample(ArtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int deleteByExample(ArtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int insert(ArtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int insertSelective(ArtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    List<ArtCategory> selectByExample(ArtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    ArtCategory selectByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ArtCategory record, @Param("example") ArtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ArtCategory record, @Param("example") ArtCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArtCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_category
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArtCategory record);
}