package com.cr.art.dao.mapper;

import com.cr.art.dao.model.ArtCommentM;
import com.cr.art.dao.model.ArtCommentMExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArtCommentMMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int countByExample(ArtCommentMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int deleteByExample(ArtCommentMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int insert(ArtCommentM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int insertSelective(ArtCommentM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	List<ArtCommentM> selectByExample(ArtCommentMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	ArtCommentM selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ArtCommentM record,
			@Param("example") ArtCommentMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ArtCommentM record,
			@Param("example") ArtCommentMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ArtCommentM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_comment
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ArtCommentM record);
}