package com.cr.art.dao.mapper;

import com.cr.art.dao.model.ArtInfoM;
import com.cr.art.dao.model.ArtInfoMExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArtInfoMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int countByExample(ArtInfoMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int deleteByExample(ArtInfoMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String artId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int insert(ArtInfoM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int insertSelective(ArtInfoM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    List<ArtInfoM> selectByExample(ArtInfoMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    ArtInfoM selectByPrimaryKey(String artId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ArtInfoM record, @Param("example") ArtInfoMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ArtInfoM record, @Param("example") ArtInfoMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArtInfoM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArtInfoM record);
}