package com.cr.art.dao.mapper;

import com.cr.art.dao.model.ArtLoginM;
import com.cr.art.dao.model.ArtLoginMExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArtLoginMMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int countByExample(ArtLoginMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int deleteByExample(ArtLoginMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int insert(ArtLoginM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int insertSelective(ArtLoginM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	List<ArtLoginM> selectByExample(ArtLoginMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	ArtLoginM selectByPrimaryKey(String id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ArtLoginM record,
			@Param("example") ArtLoginMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ArtLoginM record,
			@Param("example") ArtLoginMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ArtLoginM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_login
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ArtLoginM record);
}