package com.cr.art.dao.mapper;

import com.cr.art.dao.model.ArtOrderM;
import com.cr.art.dao.model.ArtOrderMExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArtOrderMMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int countByExample(ArtOrderMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int deleteByExample(ArtOrderMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int insert(ArtOrderM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int insertSelective(ArtOrderM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	List<ArtOrderM> selectByExample(ArtOrderMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	ArtOrderM selectByPrimaryKey(String orderId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ArtOrderM record,
			@Param("example") ArtOrderMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ArtOrderM record,
			@Param("example") ArtOrderMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ArtOrderM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_order
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ArtOrderM record);
}