package com.cr.art.dao.mapper;

import com.cr.art.dao.model.ArtPicM;
import com.cr.art.dao.model.ArtPicMExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArtPicMMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int countByExample(ArtPicMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int deleteByExample(ArtPicMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int insert(ArtPicM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int insertSelective(ArtPicM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    List<ArtPicM> selectByExample(ArtPicMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    ArtPicM selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") ArtPicM record, @Param("example") ArtPicMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") ArtPicM record, @Param("example") ArtPicMExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ArtPicM record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table art_pic
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ArtPicM record);
}