package com.cr.art.dao.mapper;

import com.cr.art.dao.model.ArtUserM;
import com.cr.art.dao.model.ArtUserMExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ArtUserMMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int countByExample(ArtUserMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int deleteByExample(ArtUserMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int insert(ArtUserM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int insertSelective(ArtUserM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	List<ArtUserM> selectByExample(ArtUserMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	ArtUserM selectByPrimaryKey(String userId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int updateByExampleSelective(@Param("record") ArtUserM record,
			@Param("example") ArtUserMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int updateByExample(@Param("record") ArtUserM record,
			@Param("example") ArtUserMExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(ArtUserM record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table art_user
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ArtUserM record);
}